fixed SVGs in events page
ReflectionsProjections/rp-mobile-2024 pull request #26
Opened 2024-08-19 23:59 UTC by aryan-bhardwaj

Fixed SVGs in events page

2024-08-21 02:46 UTC, divyack2 requested changes
just remove commented lines of code and this is good to go!

2024-08-21 02:46 UTC, divyack2 commented on components/EventCard.tsx
> +    // alignItems: 'center',
remove comments

2024-08-21 20:16 UTC, aryan-bhardwaj commented on components/EventCard.tsx
> +    // alignItems: 'center',
done!

2024-08-23 02:44 UTC, divyack2 approved these changes

2024-08-23 19:32 UTC, merged